### ISSUE TITLE
Feature request: support for multiple organizations where the username and login for the organizations are different

### ISSUE THREAD

**Issue by tooh** [johnthepink/alfred2-basecamp#2]

**Comment by johnthepink** [comment]
Thanks for the request! Basecamp has said they will merge accounts for you if you contact their support: https://twitter.com/37signals/status/235071568236138496

Would that fix your issue? Or does it make sense to support multiple accounts?

**Comment by johnthepink** [comment]
Closing for now. Feel free to open back up @tooh if you have more thoughts.
