### ISSUE TITLE
Fatal error on searching for projects

### ISSUE THREAD

**Issue by sharat** [johnthepink/alfred2-basecamp#3]
Getting this error. How do I resolve this?

```
[2015-04-06 12:47:34 #2127] ERROR -- me.johnpinkerton.alfred2-basecamp: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<NoMethodError: undefined method `split' for nil:NilClass>
  ./main.rb:26:in `block in <main>'
/Users/sarat/Dropbox/Alfred Settings/Alfred.alfredpreferences/workflows/user.workflow.6B61E10B-6A93-4E2E-85A5-5D3B0029FAD8/bundle/ruby/2.1.0/gems/alfred-workflow-1.8.0/lib/alfred.rb:29:in `with_friendly_error'
./main.rb:12:in `<main>'
```

**Comment by johnthepink** [comment]
Looks like that is an issue with your settings. Did you configure your information here?

![screenshot 2015-04-06 08 32 13](https://cloud.githubusercontent.com/assets/816517/7004315/85b15664-dc37-11e4-9e22-8f47cd5da539.png)

**Comment by johnthepink** [comment]
Any luck with this @sharat ?

**Comment by sharat** [comment]
@johnthepink It's working now. Somehow I specified everything within an `[ ]` 

My bad :cry:

**Comment by johnthepink** [comment]
no worries @sharat. glad you got it figured out :smile_cat:

**Comment by sharat** [comment]
@johnthepink thanks John. Life is so much better with Workflows and 1Password these days :)

**Comment by johnthepink** [comment]
I completely agree @sharat
