### ISSUE TITLE
Only shows 15 results

### ISSUE THREAD

**Issue by whispy** [johnthepink/alfred2-basecamp#9]
I've added my token and key for my Basecamp 3 account. When typing `bc ! <characters>`, only the first 15 projects are shown.

Is this an API limitation?

Happy to provide more info, if required.

EDIT: Not the *first* 15. Just a selection of 15. I'm not sure if there are any similarities between the 15 that are shown. Maybe most recently created projects?

**Comment by johnthepink** [comment]
@whispy good question. I'm not sure at this time, but I can look in to it soon. Thanks for the report!

**Comment by gg67** [comment]
Any updates here? I am running into a _maybe_ similar issue? I believe it's a pagination issue - https://github.com/basecamp/bc3-api/blob/master/README.md#pagination

**Comment by gg67** [comment]
Should now be resolved by https://github.com/johnthepink/alfred2-basecamp/pull/11#pullrequestreview-446917290

**Comment by johnthepink** [comment]
Version 2.1.2 has been published on Packal, and is available in the repo. Let me know if you still have issues with this. Thanks @gg67!
